@ECHO OFF

SET LIB_PATH=..\lib
SET OUTPUT_FOLDER=..\bin

SET CLASSPATH=%OUTPUT_FOLDER%;%LIB_PATH%\terasoluna-batch-3.2.0.jar

SET CLASSPATH=%CLASSPATH%;%LIB_PATH%\aspectjweaver-1.6.12.jar
SET CLASSPATH=%CLASSPATH%;%LIB_PATH%\cglib-nodep-2.1_3.jar
SET CLASSPATH=%CLASSPATH%;%LIB_PATH%\commons-beanutils-1.8.3.jar
SET CLASSPATH=%CLASSPATH%;%LIB_PATH%\commons-collections-3.2.jar
SET CLASSPATH=%CLASSPATH%;%LIB_PATH%\commons-dbcp-1.2.2.patch_DBCP264_DBCP372.jar
SET CLASSPATH=%CLASSPATH%;%LIB_PATH%\commons-digester-1.8.jar
SET CLASSPATH=%CLASSPATH%;%LIB_PATH%\commons-jxpath-1.3.jar
SET CLASSPATH=%CLASSPATH%;%LIB_PATH%\commons-lang-2.5.jar
SET CLASSPATH=%CLASSPATH%;%LIB_PATH%\commons-logging-1.1.1.jar
SET CLASSPATH=%CLASSPATH%;%LIB_PATH%\commons-pool-1.6.jar
SET CLASSPATH=%CLASSPATH%;%LIB_PATH%\commons-validator-1.3.1.jar
SET CLASSPATH=%CLASSPATH%;%LIB_PATH%\mybatis-2.3.5.jar
SET CLASSPATH=%CLASSPATH%;%LIB_PATH%\jakarta-oro-2.0.8.jar
SET CLASSPATH=%CLASSPATH%;%LIB_PATH%\log4j-1.2.16.jar
SET CLASSPATH=%CLASSPATH%;%LIB_PATH%\spring-modules-validation-0.8.jar
SET CLASSPATH=%CLASSPATH%;%LIB_PATH%\terasoluna-batch-update-1.1.2.jar
SET CLASSPATH=%CLASSPATH%;%LIB_PATH%\terasoluna-collector-1.1.0.jar
SET CLASSPATH=%CLASSPATH%;%LIB_PATH%\terasoluna-commons-2.0.5.0.jar
SET CLASSPATH=%CLASSPATH%;%LIB_PATH%\terasoluna-dao-2.0.5.0.jar
SET CLASSPATH=%CLASSPATH%;%LIB_PATH%\terasoluna-filedao-2.0.3.2.jar
SET CLASSPATH=%CLASSPATH%;%LIB_PATH%\terasoluna-ibatis-2.0.5.0.jar
SET CLASSPATH=%CLASSPATH%;%LIB_PATH%\terasoluna-validator-2.0.5.0.jar
SET CLASSPATH=%CLASSPATH%;%LIB_PATH%\terasoluna-logger-1.0.0.jar
SET CLASSPATH=%CLASSPATH%;%LIB_PATH%\spring-aop-3.1.3.RELEASE.jar
SET CLASSPATH=%CLASSPATH%;%LIB_PATH%\spring-asm-3.1.3.RELEASE.jar
SET CLASSPATH=%CLASSPATH%;%LIB_PATH%\spring-beans-3.1.3.RELEASE.jar
SET CLASSPATH=%CLASSPATH%;%LIB_PATH%\spring-context-3.1.3.RELEASE.jar
SET CLASSPATH=%CLASSPATH%;%LIB_PATH%\spring-core-3.1.3.RELEASE.jar
SET CLASSPATH=%CLASSPATH%;%LIB_PATH%\spring-expression-3.1.3.RELEASE.jar
SET CLASSPATH=%CLASSPATH%;%LIB_PATH%\spring-jdbc-3.1.3.RELEASE.jar
SET CLASSPATH=%CLASSPATH%;%LIB_PATH%\spring-orm-3.1.3.RELEASE.jar
SET CLASSPATH=%CLASSPATH%;%LIB_PATH%\spring-tx-3.1.3.RELEASE.jar
SET CLASSPATH=%CLASSPATH%;%LIB_PATH%\aopalliance-1.0.jar

SET CLASSPATH=%CLASSPATH%;%LIB_PATH%\ojdbc5.jar
SET CLASSPATH=%CLASSPATH%;%LIB_PATH%\postgresql-8.4-702.jdbc3.jar
SET CLASSPATH=%CLASSPATH%;%LIB_PATH%\sqljdbc.jar
